handlers = java.util.logging.ConsoleHandler
.level = INFO
java.util.logging.ConsoleHandler.level = ALL
java.util.logging.ConsoleHandler.formatter = java.util.logging.SimpleFormatter
java.util.logging.SimpleFormatter.format = %5$s %n

org.sigmod.tcc.pcsr.analysis.TwoPassTBFSApp1.level = INFO
org.sigmod.tcc.adjlist.analysis.ReverseScanApp1.level = INFO
org.sigmod.tcc.csr.analysis.TimeCentricApp1.level = INFO
